### ISSUE TITLE
No local documentation of the binaries

### ISSUE THREAD

**Issue by olebole** [Caltech-IPAC/Montage#10]
There is no documentation of the binaries in the package; the only available is on the web page. Usually, binaries on Unix are however documented in a manpage, so one would expect the same here. Also, this is a requirement for packages on Debian (where I am the maintainer of montage) and other distributions.

The online documentation is, however, already mainly structured like manpages, so it is possible to [create somehow manpages from the html](https://anonscm.debian.org/cgit/debian-astro/packages/montage.git/tree/debian/create_man.py); however with quite a few glitches. IMO it would be better vice versa: create the online documentation from the manpages. Like it is f.e. done in the Debian manpages; see f.e. the [mProject](https://manpages.debian.org/testing/montage/mProject.1.en.html) there.

Would it be possible to distribute manpages together with the source code and maybe just create the online pages from them?

**Comment by JohnGood** [comment]
While we have maintained a presence for Montage on GitHub for a several years now,
until recently the actual source code control and issue tracking were done through
other, institution-specific, tools.  So while we addressed all issues in a timely
manner, we were regrettably lax about cleaning up these issues in GitHub.

We are going to leave this issue open.  It is perfectly doable but time consuming and
we haven't yet prioritized it.

**Comment by JohnGood** [comment]
Since I see you have already done this for Debian (thanks for that) I'm going to close this issue but will be sure to generate new manpages for any new modules and review update your existing ones.  Let me know if we can also redistribute your pages.

**Comment by olebole** [comment]
This would be great, and sure you have the permission (it is text authored by you, just reformatted). Thank you! :+1:
