### ISSUE TITLE
Undocumented binaries

### ISSUE THREAD

**Issue by olebole** [Caltech-IPAC/Montage#11]
The following executables are completely undocumented in the [online API documentation](http://montage.ipac.caltech.edu/docs/index2.html):

* mCalExec
* mCalibrate
* mCatSearch
* mDAGGalacticPlane
* mFixHdr
* mProjectQL
* mTblExec

**Comment by JohnGood** [comment]
While we have maintained a presence for Montage on GitHub for a several years now,
until recently the actual source code control and issue tracking were done through
other, institution-specific, tools.  So while we addressed all issues in a timely
manner, we were regrettably lax about cleaning up these issues in GitHub.

We are closing this issue as most of these functions are now deprecated and the 
remaining one (mProjectQL) has been documented.
