### ISSUE TITLE
Consider contributing healpix + toast patches to mainline wcstools

### ISSUE THREAD

**Issue by olebole** [Caltech-IPAC/Montage#14]
When looking into the wcstools changes, I am wondering if the healpy and toast projections would be useful in the mainstream wcstools as well? Would you consider contributing them to Jessica Mink so that they can be integrated there? This would have at once the advantage that not only montage could profit from it, but it would also allow these projections to be used on modular build approaches (like for Debian, where locally copied libraries are discouraged).

**Comment by JohnGood** [comment]
While we have maintained a presence for Montage on GitHub for a several years now,
until recently the actual source code control and issue tracking were done through
other, institution-specific, tools.  So while we addressed all issues in a timely
manner, we were regrettably lax about cleaning up these issues in GitHub.

We contributed these projections some time ago.
