### ISSUE TITLE
pack file almost seven times larger than the source code

### ISSUE THREAD

**Issue by scizen9** [Caltech-IPAC/Montage#2]
The .git/objects/pack/ directory is 740Mb, while the rest of the repository is 119 Mb.  Most likely this is due to historical records that may or may not be needed.  This repository took an inordinate amount of time to fork (or clone).  I would suggest that the maintainers at least look into the possibility of pruning the history to create a more reasonable sized repository.  If this is considered a reasonable request (there may be good reasons why it is not), a google search on 'git pack file large' should offer some avenues to explore.

**Comment by JohnGood** [comment]
You were correct; there were some large data files that had been added inadvertently and then deleted.  The size should be more appropriate now.
