### ISSUE TITLE
Mistake in docs for mBgExec

### ISSUE THREAD

**Issue by astrofrog** [Caltech-IPAC/Montage#20]
I think the first line of http://montage.ipac.caltech.edu/docs/mBgExec.html should mention mBgModel not mFitExec?

**Comment by danielskatz** [comment]
I think mFitExec is correct - this is the tool that builds the fits.  See the top of http://montage.ipac.caltech.edu/docs/mFitExec.html and the overall flow of tools in http://montage.ipac.caltech.edu/docs/m101tutorial.html
