### ISSUE TITLE
mExec failing with Montage 4.0 and 5.0

### ISSUE THREAD

**Issue by astrofrog** [Caltech-IPAC/Montage#22]
The following example fails with Montage 4.0 and 5.0 but works with 3.3:

```
$ mExec -n 1 -m 1 -l -c -o test_mosaic.fits -f full_header.hdr 2MASS k
[struct stat="ERROR", msg="Usage: rimages.tbl [-s statusfile] in.tbl out.tbl -<mode> <parameters> [where mode can be 'points', 'box', 'circle', 'header', 'point' or 'cutout'"]
```

where ``full_header.hdr`` is:

```
SIMPLE  = T
BITPIX  = -64
NAXIS   = 2
NAXIS1  = 1328
NAXIS2  = 2203
CTYPE1  = 'RA---TAN'
CTYPE2  = 'DEC--TAN'
EQUINOX = 2000
CRVAL1  =   10.715471592
CRVAL2  =   41.220666214
CRPIX1  =       664.5000
CRPIX2  =      1102.0000
CDELT1  =   -0.000277780
CDELT2  =    0.000277780
CROTA2  =    0.109236647
END
```

**Comment by JohnGood** [comment]
While we have maintained a presence for Montage on GitHub for a several years now,
until recently the actual source code control and issue tracking were done through
other, institution-specific, tools.  So while we addressed all issues in a timely
manner, we were regrettably lax about cleaning up these issues in GitHub.

This command works with both the current "main" and "develop" branches in GitHub.
