### ISSUE TITLE
helpdesk link not working?

### ISSUE THREAD

**Issue by teuben** [Caltech-IPAC/Montage#29]
On the documentation page the helpdesk is listed as:
     http://vaoweb2.ipac.caltech.edu/cgi-bin/Helpdesk/nph-genTicketForm
but that site doesn't seem to be up.

**Comment by JohnGood** [comment]
There was on place in the on-line site documentation ("Contributed Software" page) where this link occurred and that has now been fixed.  We could not find any others but let us know if you do.
