### ISSUE TITLE
mSubimage copies HDU's but also changes the bitpix

### ISSUE THREAD

**Issue by teuben** [Caltech-IPAC/Montage#31]
This follows a private discussion with John Good, about how to promote an image extension to a primary HDU for software that doesn't know how to deal with extensions (very useful btw).

For example I grabbed a testfile with the following python snippet:

from astropy.io import fits
from astroquery.mast import Observations
obsid = '2004615006'
Observations.download_products(obsid,productFilename="iczgs3ygq_flt.fits")
test_file = './mastDownload/HST/ICZGS3YGQ/iczgs3ygq_flt.fits'

this gives a file with 

Filename: ./mastDownload/HST/ICZGS3YGQ/iczgs3ygq_flt.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU     265   ()
  1  SCI           1 ImageHDU       140   (1014, 1014)   float32
  2  ERR           1 ImageHDU        51   (1014, 1014)   float32
  3  DQ            1 ImageHDU        43   (1014, 1014)   int16
  4  SAMP          1 ImageHDU        37   (1014, 1014)   int16
  5  TIME          1 ImageHDU        37   (1014, 1014)   float32
  6  WCSCORR       1 BinTableHDU     59   7R x 24C   [40A, I, A, 24A, 24A, 24A, 24A, D, D, D, D, D, D, D, D, 24A, 24A, D, D, D, D, J, 40A, 128A]

the following command

mSubimage -c -h 1 iczgs3ygq_flt.fits junk1.fits

gives a bitpix=-64 image:

Filename: mastDownload/HST/iczgs3ygq/junk1.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  SCI           1 PrimaryHDU     141   (1014, 1014)   float64   

which is not what I would expect to be the default action. It should not add information to the image :-)

**Comment by JohnGood** [comment]
It was broken but you are also using the wrong flag:

   mSubimage in.fits out.fits ra dec xsize ysize     Extracts xsize by ysize in degrees centered on (RA,Dec).
   mSubimage -p in.fits out.fits startpix1 startpix2 xpix ypix     Extracts xpix by ypix starting at (startpix1,startpix2).
   mSubimage -P in.fits out.fits startpix1 startpix2 xpix ypix     Same but relative to CRPIX1,CRPIX2.
   mSubimage -a -hdu 1 in.fits out.fits     Extracts all the pixels for HDU1.
   mSubimage -c in.fits out.fits     Extracts all the pixels but crops any blank/NaN border.
