### ISSUE TITLE
mJPEG is not compiled

### ISSUE THREAD

**Issue by david-guyon** [Caltech-IPAC/Montage#34]
In [this commit](https://github.com/Caltech-IPAC/Montage/commit/b287a1382bf5a42c8a67a69cbf63af2ff523539d#diff-8b8d57c3a9b1ec25f6110dba11010c7a) from May 15, 2018, I can see you removed the compilation of ``mJPEG``. 

I added this line to the ``all`` rule of util/Makefile to get ``mJPEG``:

```
-(cd JPEG; ./Configure.sh; make; make install)
```

Is it normal that this line has been removed?

**Comment by RRPJ** [comment]
According to #4 mJPEG has been replaced by mViewer. 

To the authors, you may want to update the tutorial at http://montage.ipac.caltech.edu/docs/m101tutorial.html. It still has mJPEG.

**Comment by david-guyon** [comment]
Thanks! As you said, it would be great to update the documentation (maybe someone should open a new Github issue).

Then I guess I can close this issue.
