### ISSUE TITLE
Makefiles do not stop on error

### ISSUE THREAD

**Issue by olebole** [Caltech-IPAC/Montage#35]
A compilation error is not propagated in the current Makefile system due to the currently used Makefile syntax, f.e. https://github.com/Caltech-IPAC/Montage/blob/31e56d349f77170bdd4ccc17800312be0f215da3/util/Makefile#L1-L4

- commands are executed in a subshell and concatenated with `;` instead of `&&`
- command lines are start with `-`, causing ignorance of any error code

Together with missing build time tests, it is practically impossible to find out whether a compilation was successful, especially not in an automated way. This makes it *very* hard to package Montage for Debian and other systems: We use an automated build system for ~24 architectures, with automated rebuilds on ABI changes, and with automated builds on downstream distributions (like Ubuntu or Mint).

Would it be possible to change the build system so that it stops on error?

This topic was basically brought up by people wanting to cross compile Montage. They opened the bug [Debian#915163](https://bugs.debian.org/915163) for the Debian package.

**Comment by JohnGood** [comment]
Makefiles changed.
