### ISSUE TITLE
mJPEG bug

### ISSUE THREAD

**Issue by masa16** [Caltech-IPAC/Montage#4]
mJPEG does not work correctly since the variable `nan' is not defined in getRange() function in mJPEG.c. It probably sees the function nan(3) in math.h.

**Comment by JohnGood** [comment]
mJPEG has been superceded by mViewer, which has the same calling
syntax but is extended in several ways (PNG output option, various
overlays, etc.)    It also has fairly complete tutorial documentation at

http://montage.ipac.caltech.edu/mViewer/

mViewer has already had this problem addressed but we have now
updated mJPEG as well.  Thanks for the feedback.
