### ISSUE TITLE
Reference for citation

### ISSUE THREAD

**Issue by martinberoiz** [Caltech-IPAC/Montage#42]
Hello,

I've been looking for a proper reference to cite Montage and I couldn't seem to find one. Is there a DOI or a seminal paper on the algorithms, that I could cite?

Thanks!

**Comment by GBruceB** [comment]
We have been planning a seminal paper on all the latest features, but it's not ready for submission. In the meantime, may I suggest you quote:

G. Bruce Berriman and J. C. Good 2017 PASP 129 058006.
https://doi.org/10.1088/1538-3873/aa5456

and

Montage: a grid portal and software toolkit for science-grade astronomical image mosaicking
by Joseph C. Jacob, Daniel S. Katz, G. Bruce Berriman, John C. Good, Anastasia C. Laity, Ewa Deelman, Carl Kesselman, Gurmeet Singh, Mei-Hui Su, Thomas A. Prince, Roy Williams
International Journal of Computational Science and Engineering (IJCSE), Vol. 4, No. 2, 2009

Cheers

Bruce Berriman

**Comment by martinberoiz** [comment]
Thank you
