### ISSUE TITLE
Projection errors and possible solution

### ISSUE THREAD

**Issue by fardal** [Caltech-IPAC/Montage#45]
Using mProjExec, I got unreliable behavior when projecting small images to an all-sky projection.  Nonzero pixels appeared in areas outside of the sky oval, and regions within the sky oval were corrupted.  The exact pattern differed from run to run.  Sometimes it would succeed with no obvious glitches, but this was extremely inconsistent: it appeared to depend on whether I ran with MPI on or off, the number of images projected, whether I ran inside or outside a jupyter notebook, and waiting a while and rerunning could produce different results.  This was on Mac OS X 10.13.6.  My one test with linux produced no apparent glitches.

If I change line 280 in MontageLib/Project/montageProject.c from
   `int       haveIn, haveOut, haveMinMax, haveTop;`
to read
   `int       haveIn, haveOut, haveMinMax, haveTop=0;`
this glitchy behavior goes away, at least so far.  The behavior I saw looked like it could be related to either memory errors or uninitialized variables, so this might make sense.

**Comment by JohnGood** [comment]
That initialization inadvertently got lost when we converted the code to library form.  Thanks for finding it; we have updated the code and should be uploading to GitHub shortly.
