### ISSUE TITLE
possible bug in Montage/util/Exec/mExec.c

### ISSUE THREAD

**Issue by izff** [Caltech-IPAC/Montage#47]
The int variable "icntr" is used on line 2421 but was never assigned a value.

I think the intended value was always 0; on some platform, like my mac with gcc 4.2.1, the default value is indeed 0; that's why mExec worked correctly on my mac.

However, on my Linux server with gcc 4.4.7, I don't know why but the default value for "icntr" is 1 instead of 0; as a result, mExec failed.

A simple fix would be assigning "icntr" after opening "pimage.tbl" on line 2410,
using tcol:

icntr = tcol('cntr');

Hope that I can get some confirmation on this issue. Thanks!

**Comment by JohnGood** [comment]
While we have maintained a presence for Montage on GitHub for a several years now,
until recently the actual source code control and issue tracking were done through
other, institution-specific, tools.  So while we addressed all issues in a timely
manner, we were regrettably lax about cleaning up these issues in GitHub.

This bug has been fixed.
