### ISSUE TITLE
unable to build montage

### ISSUE THREAD

**Issue by akritiasto** [Caltech-IPAC/Montage#48]
I am trying to build montage on fedora 30. I followed the steps:
cloned from github(https://github.com/Caltech-IPAC/Montage)
type "make" to build montage

I am getting the following error:
gcc -o mConvert mConvert.o debugCheck.o checkHdr.o \
	checkWCS.o -L../lib -lwcs -lcfitsio -lcoord -lmtbl -lsvc -lwww -lboundaries -lpixbounds -ltwoplane -lnsl -lm
/usr/bin/ld: cannot find -lnsl
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:114: mConvert] Error 1
make[1]: Leaving directory '/home/akriti/Montage/Montage'
make: *** [Makefile:5: all] Error 2

Kindly help resolve this issue

**Comment by JohnGood** [comment]
The NSL library deals with networking issues and until now has been standard on all LINUX platforms.  Apparently, Fedora (as of version 28; May 2018) no longer includes (or needs) 
libnsl.  

There are a few places in Montage where we do simple Makefile configuration based on the
OS version.  Fedora still claims to be generic LINUX but is different from other LINUX 
distributions in this regard.  Until we have a chance to update the logic, you will have to
manually edit the "-lnsl" out of the library list wherever it causes you trouble.

**Comment by JohnGood** [comment]
While we have maintained a presence for Montage on GitHub for a several years now,
until recently the actual source code control and issue tracking were done through
other, institution-specific, tools.  So while we addressed all issues in a timely
manner, we were regrettably lax about cleaning up these issues in GitHub.

All our Makefiles have been updated to avoid this problem.
