### ISSUE TITLE
Using -O2

### ISSUE THREAD

**Issue by Derrior** [Caltech-IPAC/Montage#50]
Why don't you use -O2 compiler option? I used it locally and mProject, for example, became 60% faster

**Comment by JohnGood** [comment]
While we have maintained a presence for Montage on GitHub for a several years now,
until recently the actual source code control and issue tracking were done through
other, institution-specific, tools.  So while we addressed all issues in a timely
manner, we were regrettably lax about cleaning up these issues in GitHub.

This flag has been added throughout our code.
