### ISSUE TITLE
man page URL via --help

### ISSUE THREAD

**Issue by teuben** [Caltech-IPAC/Montage#53]
when montage is installed, i can't find the man pages.  I know they are online, but it requires an extra step, and yes, it requires internet. murphy's law dictactes i'm going to need a man page when i don't have internet.

However, in the mean time, I have one suggestion.    If I  say
     mAdd --help
it probably satisfies most regular users, but if it would also give the link, i.e.
    http://montage.ipac.caltech.edu/docs/mAdd.html
I get to see lots of useful info, plus more.

In my terminal, any url that is output and if the mouse hovers over it,  the url gets underlined , a right click will give an option to open the link, etc.  Very useful   (i have built this feature into my own NEMO package since the link follows a simple pattern, which montage also seems to follow).

**Comment by olebole** [comment]
Manpages are included in the [Debian (and Ubuntu) package](https://packages.debian.org/sid/amd64/montage/filelist) of Montage. [This](https://manpages.debian.org/testing/montage/mAdd.1.en.html) is a web version of them, but they are accessible with `man mAdd`.

**Comment by JohnGood** [comment]
We will include the Debian-generated man pages if given permission and will maintain and extend them.

**Comment by olebole** [comment]
This would be great, and sure you have the permission (it is text authored by you, just reformatted). Thank you! :+1:
