### ISSUE TITLE
mCatMap man page example does not work , hdr formar clarification

### ISSUE THREAD

**Issue by teuben** [Caltech-IPAC/Montage#54]
the example
       mCatMap -c flux 2mass_pt.tbl 2mass_pt.fits 2mass_pt.hdr
is great , because the files are there!
But it didn't work, there is no column named flux in that table.   I used j_m, since it worked, but the -m flag suggests.

But while you are at it, the description of the hdr template file should be clarified. It now says, taken from http://montage.ipac.caltech.edu/docs/headers.html

_with two exceptions: they don't need to be padded to 80 characters on each line, and each line ends in a newline._

your example has exactly the spacings correct for a fits header, but I found out by experiment that using less (or even none) spaces works just as well, so it should be clarified, otherwise people are going to waste time counting spaces, putting the = sign in column 9 etc.

**Comment by JohnGood** [comment]
Thanks, its been updated and augmented with a better example.
