### ISSUE TITLE
Compile for MacOS Big sur

### ISSUE THREAD

**Issue by dxcore35** [Caltech-IPAC/Montage#55]
I tried to compile the source code for myself, but I got bunch of errors.
It will be amazing if somebody can compile it for MacOS big sur, as the oldest 10.7 is not compatible.

Thanks a lot!

**Comment by JohnGood** [comment]
With Big Sur, some older system libraries have been deprecated.  This didn't affect our code but did affect the CFITSIO library so we had to update that in our distribution.  We made a specific branch off "main" for this called "update_cfitsio" and have also incorporated the change in the "develop" branch which we hope to release shortly.
