### ISSUE TITLE
building on centos8 fails? / no make install?

### ISSUE THREAD

**Issue by teuben** [Caltech-IPAC/Montage#56]
I'm always impressed how clean Montage builds with just a simple 'make'. But somehow Centos8 (yes, the one that's disappearing) is now failing for me. Linking failed with -lnsl not found. Indeed, there is some libnsl and libnsl2 switch. Could be that redhat8 has a similar fate.

On a related note, there is no "make install", would be nice to have with a PREFIX= option for this. I know, right now it's just copying the bin contents to the PREFIX/bin, but it saves some people from having to explain others to modify their dot file (always a challenging request)

**Comment by teuben** [comment]
Small update: with a "yum install libnsl2-devel" i was able to get past the -lnsl linking failure, but now very oddly , some symbols are defined twice. Rarely see those these days:

gcc -o mConvert mConvert.o debugCheck.o checkHdr.o \
	checkWCS.o -L../lib -lwcs -lcfitsio -lcoord -lmtbl -lsvc -lwww -lboundaries -lpixbounds -ltwoplane -lnsl -lm
/usr/bin/ld: debugCheck.o:/home/osboxes/LMT/lmtoy/Montage/Montage/montage.h:2: multiple definition of `fstatus'; mConvert
.o:/home/osboxes/LMT/lmtoy/Montage/Montage/montage.h:2: first defined here
/usr/bin/ld: checkHdr.o:/home/osboxes/LMT/lmtoy/Montage/Montage/montage.h:2: multiple definition of `fstatus'; mConvert.o
:/home/osboxes/LMT/lmtoy/Montage/Montage/montage.h:2: first defined here
/usr/bin/ld: checkWCS.o:/home/osboxes/LMT/lmtoy/Montage/Montage/montage.h:2: multiple definition of `fstatus'; mConvert.o
:/home/osboxes/LMT/lmtoy/Montage/Montage/montage.h:2: first defined here

this is gcc 10.2.1

**Comment by teuben** [comment]
Another observation: Using something like

       CC=gcc-10 make

resulting on *some* programs to use gcc-10, but others (e.g. mProjExec to be compiled with gcc.   So, the CC variable is not properly passed through.   This sounds a  bit like #12 

Editing the Makefile in Montage confirmed the bug, with gcc-10 duplicate linking happens. I suspect wrong declaration in a header file, An object should be defined in the c fiel, and declared extern in the header? Somehow the linker can't overlay this, i've seen this error before. Maybe with another compile flag it could work.

Also wondering why github isn't making a link to #12  It's not my day, i should not work this late.

**Comment by teuben** [comment]
Also to note:     if I remove  -lnsl    from the linker options in the offending Montage/Makefile, it works ...... so maybe we don't need this library anymore?  [as on Darwin] These are a relic from the good old SunOS NIS/NIS+ days?

**Comment by JohnGood** [comment]
We had already concluded that -lnsl is now no longer needed anywhere and have revamped all the Makefiles in the "develop" version.  I'm looking at the other issues now.

**Comment by JohnGood** [comment]
I will switch our Makefiles to use the CC implicit variable.  This will be done in the "develop" branch shortly.
