### ISSUE TITLE
MontagePy Latest Release Doesn't Include whl files for Linux

### ISSUE THREAD

**Issue by ryanhausen** [Caltech-IPAC/Montage#57]
Thanks for the great tool!

The latest version of MontagePy seems to only have macosx wheel files.

![Selection_066](https://user-images.githubusercontent.com/13540823/114769531-2d085580-9d1f-11eb-87e0-dc926f7a87ab.png)

The previous version does, but doesn't include a version for Python 3.8.

Will linux be supported in the next version release and in 3.8? 

Thanks!

**Comment by JohnGood** [comment]
Wheels for Linux/Python 2.7 and 3.6-3.9 have been uploaded to PyPI.  The OSX wheels don't include 3.9; we use Anaconda and it hasn't released a 3.9 version yet.
